### ISSUE TITLE
显示乱码

### ISSUE THREAD

**Issue by zuoyi93** [devilyouwei/NVimmer#1]
您好，

非常感谢分享这个工具！我在安装完成后发现nvim显示有乱码，Monaco的字体我已经装好。不知道哪里没有配置对，请问您可以解答一下吗？

![Screenshot from 2021-08-03 14-34-14](https://user-images.githubusercontent.com/25957920/128076301-97252cf3-599f-4b25-98e5-a1de90644b36.png)

谢谢！

**Comment by zuoyi93** [comment]
您好，

我使用的Ubuntu 20.04系统。我发现Monaco字体无法在terminal里加载，于是我有下载了另一个nerd font,名字是Hack. 这个字体可以加载在terminal里，但是重启后仍然无法加载nerdtree的图标。请问您之前遇到过这种情况吗？

谢谢！

**Comment by zuoyi93** [comment]
我后来通过下载一个字体名里带有Nerd的字体，解决了这个问题。希望可以帮到后面看到问题的朋友。

打扰了。

**Comment by devilyouwei** [comment]
https://github.com/devilyouwei/linux-font/tree/master/Monaco/Nerd

这是我组装的nerd字体，ubuntu可以下载`YaheiMonacoNerd.ttf`

但是下载过后，你依旧无法在terminal字体中找到，这似乎是18.04后的问题，你可以使用gnome tweak修改字体，如下配置

![image](https://user-images.githubusercontent.com/7458256/128124764-3b840bc0-9c91-4cfb-99ba-e638696aacf6.png)

**Comment by devilyouwei** [comment]
About nerdfonts, you can refer to this repo

https://github.com/lambdalisue/nerdfont.vim

**Comment by devilyouwei** [comment]
About nerd fonts, refer to this repo, without nerd fonts, you will lose icon fonts in the terminal
https://github.com/ryanoasis/nerd-fonts

**Comment by zuoyi93** [comment]
谢谢回复，学到了
